.PHONY: build test fuzz fuzz-build fmt fmt-check lint doc clean deploy-testnet wasm-build wasm-optimize wasm-build-optimized docker-build docker-build-verify coverage

# ── Build ────────────────────────────────────────────────────────────────────

## build: Compile the contract to WASM (release profile, wasm32 target)
build: wasm-build

## wasm-build: Explicit WASM release build (output: target/wasm32-unknown-unknown/release/*.wasm)
wasm-build:
	cargo build --release --target wasm32-unknown-unknown

## soroban-build: Build via the Stellar CLI (alternative to cargo build --target wasm32)
soroban-build:
	stellar contract build

## wasm-optimize: Run the Stellar CLI optimizer (wasm-opt) on the already-built release WASM.
##   Requires: stellar CLI installed and available on PATH.
##   Input:  target/wasm32-unknown-unknown/release/stellar_wrap_contract.wasm
##   Output: target/wasm32-unknown-unknown/release/stellar_wrap_contract.optimized.wasm
wasm-optimize:
	stellar contract optimize \
		--wasm target/wasm32-unknown-unknown/release/stellar_wrap_contract.wasm \
		--wasm-out target/wasm32-unknown-unknown/release/stellar_wrap_contract.optimized.wasm

## wasm-build-optimized: Compile to WASM (release) then apply the Stellar CLI optimizer in one step.
##   Produces both the raw and optimized WASM artifacts under
##   target/wasm32-unknown-unknown/release/.
##   Requires: stellar CLI installed and available on PATH.
wasm-build-optimized: wasm-build wasm-optimize

# ── Test ─────────────────────────────────────────────────────────────────────

## test: Run all unit and integration tests
test:
	cargo test

## test-verbose: Run all tests with stdout output (useful for gas analysis)
test-verbose:
	cargo test -- --nocapture --test-threads=1

## coverage: Run cargo-tarpaulin and generate HTML + XML reports in coverage/
##   Requires cargo-tarpaulin: cargo install cargo-tarpaulin --locked
##   Exits non-zero if line coverage falls below the fail-under threshold in
##   tarpaulin.toml (currently 90%).
coverage:
	cargo tarpaulin --config tarpaulin.toml
	@echo "Coverage report written to coverage/tarpaulin-report.html"
## test-gas-report: Run tests with full gas budget reporting enabled
test-gas-report:
	SOROBAN_GAS_REPORT=1 cargo test -- --nocapture --test-threads=1

## clean-snapshots: Remove test snapshot files generated by the Soroban test framework
clean-snapshots:
	rm -rf test_snapshots/

## clean-all: Remove build artifacts and test snapshots
clean-all: clean clean-snapshots

## fuzz-build: Build the mint_wrap cargo-fuzz target (requires nightly + cargo-fuzz + rust-src)
fuzz-build:
	cargo +nightly fuzz build --sanitizer=thread --build-std fuzz_mint_wrap

## fuzz: Run the mint_wrap fuzzer (Ctrl-C to stop; use FUZZ_SECONDS=N for a timed run)
##   Requires: rustup component add rust-src --toolchain nightly
fuzz:
	@if [ -n "$(FUZZ_SECONDS)" ]; then \
		cargo +nightly fuzz run --sanitizer=thread --build-std fuzz_mint_wrap -- -max_total_time=$(FUZZ_SECONDS); \
	else \
		cargo +nightly fuzz run --sanitizer=thread --build-std fuzz_mint_wrap; \
	fi

# ── Format ───────────────────────────────────────────────────────────────────

## fmt: Auto-format source code with rustfmt
fmt:
	cargo fmt

## fmt-check: Check formatting without modifying files (CI-safe)
fmt-check:
	cargo fmt --check

# ── Lint ─────────────────────────────────────────────────────────────────────

## lint: Run clippy and treat all warnings as errors
lint:
	cargo clippy -- -D warnings

## doc: Build contract documentation and treat warnings as errors
doc:
	RUSTDOCFLAGS="-D warnings" cargo doc --no-deps

# ── Deploy ───────────────────────────────────────────────────────────────────

## deploy-testnet: Build and deploy the contract to Stellar testnet.
##   Requires: stellar CLI, STELLAR_DEPLOYER_SECRET env var set.
##   Usage: make deploy-testnet
##   Optional: CONTRACT_ID=<id> to upgrade an existing contract instead of deploying fresh.
deploy-testnet: wasm-build
	@if [ -n "$(CONTRACT_ID)" ]; then \
		echo "Upgrading existing contract $(CONTRACT_ID)…"; \
		stellar contract upload \
			--wasm target/wasm32-unknown-unknown/release/stellar_wrap_contract.wasm \
			--network testnet \
			--source "$(STELLAR_DEPLOYER_SECRET)"; \
	else \
		echo "Deploying new contract to testnet…"; \
		stellar contract deploy \
			--wasm target/wasm32-unknown-unknown/release/stellar_wrap_contract.wasm \
			--network testnet \
			--source "$(STELLAR_DEPLOYER_SECRET)"; \
	fi

# ── Clean ────────────────────────────────────────────────────────────────────

## clean: Remove build artifacts
clean:
	cargo clean

# ── Docker ───────────────────────────────────────────────────────────────────

## docker-build: Build the contract inside Docker for reproducible WASM output
docker-build:
	docker build -t stellar-wrap-contract .

## docker-build-verify: Build in Docker and print SHA-256 of the WASM artifact
docker-build-verify:
	docker build -t stellar-wrap-contract-verify .
	docker run --rm stellar-wrap-contract-verify sha256sum /contract/target/wasm32-unknown-unknown/release/stellar_wrap_contract.wasm

# ── Help ─────────────────────────────────────────────────────────────────────

## help: List all available make targets with descriptions
help:
	@grep -E '^## ' Makefile | sed 's/## /  /'
